config/routes.rb
SurveyHuman::Application.routes.draw do

  resources :courses

  namespace :panel do resources :organizations end
  namespace :panel do resources :organization_invitations end

  get "report/index"
  namespace :panel do resources :subscription_transactions end

  get "/gateways/update-default-gateway/:id/:task", :to => "panel/gateways#update_default_gateway" ,\
  :as => 'update_default_gateway'

  get "/organization-invitation/update-status/:id/:status",
      :to => "panel/organization_invitations#update_status",
      :as => 'organization_invitation_update_status'

  post "/panel/deals/send-deal",
    :to => "panel/deals#send_deal",
    :as => 'send_deal'

  namespace :panel do
    resources :gateways do
    end
  end

  namespace :panel do resources :planfeatures end

  namespace :panel do resources :features end

  namespace :panel do resources :subscriptions end

  namespace :panel do resources :deals end

  namespace :panel do resources :plans end

  namespace :panel do resources :billings end

  resources :countries

  get "survey/index"

  get "front/sign_up"

  get "payment_notification/create"

  devise_for :users, :path => "", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }, :controllers => { :confirmations => "confirmations" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "home", :to => "devise/sessions#homepage"
    get "sign_up", :to => "devise/registrations#new"
  end

  namespace :account_management do
    resources :user do
      get :dashboard, :on => :collection
      get :account_panel, :on => :collection
      get :export_to_spreadsheet, :on => :collection
      post :create_user_by_sign_up, :on => :collection
    end
    resources :profile
    resources :log
    resources :company
  end

  namespace :match_management do
    resources :match do 
      get :match_panel, :on => :collection
      get :show_matches_by_match_type, :on => :collection
    end
    resources :survey do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_survey, :on=>:collection
      get :distribute, :on=>:collection
      put :send_survey_by_email, :on=>:collection
    end
    resources :exam do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_exam, :on=>:collection
      get :distribute, :on=>:collection
      put :send_exam_by_email, :on=>:collection
    end
    resources :match_type
    resources :question do
      post :add_question, :on=>:collection
      put :edit_question, :on=>:collection
      put :choose_correct_answer, :on=>:collection
    end
    resources :answer do
      put :add_answers, :on=>:collection
      put :edit_answers, :on=>:collection
    end
    resources :question_level
    resources :question_type
    resources :exam_topic
    resources :answer_format
    
  end

  namespace :organization_management do
    resources :company do 
      get :organization_panel, :on => :collection
    end
  end

  namespace :panel do
    resources :survey do
      post :submit_survey, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :exam do
      post :validate_user, :on => :collection
      get :forgot_password, :on => :collection
      post :send_password, :on => :collection
      get :new_code, :on => :collection
      post :create_code, :on => :collection
      get :show_exam, :on => :collection
      post :submit_exam, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :subscribe do
      get :index, :on => :collection
      get :edit, :on => :collection
      get :update, :on => :collection
    end
  end

  namespace :reports_management do
    resources :report do
      get :show_question , :on => :collection
      get :export_pdf, :on=> :collection
      get :show_result_student, :on=> :collection
      put :complete_result, :on=> :collection
    end
  end

  root :controller=>"account_management/user", :action=>"dashboard"

end

app/models/match_type.rb
class MatchType < ActiveRecord::Base
	has_many :matches

	# This function evaluates if a column is nullable or not in the database
	#
	# * *args*
	#   - column(_string_) -> database column to be evaluated
	# * *returns*
	#   - if the column is nullable or not
	def self.null?(column)
		columns_hash[column].null
	end
	
	# This function change user state to deleted
  	#
	# * *args*
	#   - id -> profile id
	# * *returns*
	#   - if the state update was successful or not
	def self.delete(id)
		return update_all({:deleted=>1, :updated_at=>Time.now},{:id=>id})
	end

end

app/controllers/match_management/answer_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::AnswerController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    @current_view = "match"
    if current_user.has_access 48
      @search = Answer.search(params[:search])
      @list_answers = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      @list_questions = Question.where(:deleted=>0)
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 49
      @answer = Answer.new
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 49
      answer = Answer.new(params[:answer])
      begin
        if answer.save
          str_desc="Se registró el answer con id = "+answer.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer)
          redirect_to :action=>"new",:answer=>answer.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:answer=>answer.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 50
      @answer = Answer.find(params[:id])
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 51
      @answer = Answer.find(params[:id])
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 51
      answer = Answer.find(params[:id])
      answer.attributes = params[:answer]

      begin
        if answer.save
          str_desc="Se editó el answer con id = "+answer.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 52
      begin
        if Answer.delete(params[:id])
          str_desc="Se eliminó el answer con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

  def add_answers
    if current_user.has_access 49
      #answer = Answer.new(params[:answer])
      question = Question.find params[:id]
      if !params[:question].nil?
        if Answer.where(:question_id=>question.id,:deleted=>0).count<=50
          params[:question][:answers_attributes].values.each do |answer|
            if answer[:_destroy]==false
                @answer=Answer.create!({:answer=>answer[:answer],:question_id=>question.id})
            end
          end
          question.attributes = params[:question]
          redirect_str= question.match.match_type_id==1 ? "/match_management/survey/#{question.match_id}/edit" : "/match_management/exam/#{question.match_id}/edit"
          begin
            if question.save
              str_desc="Se registró answers para la pregunta con id = "+question.id.to_s
              @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
              flash[:notice] = t('messages.successfully_created')
              redirect_to(redirect_str)
            else
              flash[:alert] = get_errors(answer)
              redirect_to(redirect_str)
            end
          rescue ActiveRecord::StatementInvalid => error
            flash[:alert] = t('messages.error_ocurred')
            redirect_to(redirect_str)
          end
        else
          flash[:alert] = "You cannot add more answers. Has been added 50 answers."
          redirect_to(redirect_str)
        end
      else
        redirect_str= question.match.match_type_id==1 ? "/match_management/survey/#{question.match_id}/edit" : "/match_management/exam/#{question.match_id}/edit"
        flash[:notice] = "You have not added any answer to the selected question."
        redirect_to(redirect_str)
      end
    else
      no_access
    end
  end

end

app/controllers/match_management/answer_format_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::AnswerFormatController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    @current_view = "match"
    if current_user.has_access 53
      @search = AnswerFormat.search(params[:search])
      @list_answer_formats = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 54
      @answer_format = AnswerFormat.new
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 54
      answer_format = AnswerFormat.new(params[:answer_format])
      begin
        if answer_format.save
          str_desc="Se registró el answer format "+answer_format.name+" con id = "+answer_format.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer_format)
          redirect_to :action=>"new",:answer_format=>answer_format.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:answer_format=>answer_format.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 55
      @answer_format = AnswerFormat.find(params[:id])
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 56
      @answer_format = AnswerFormat.find(params[:id])
      @list_users = User.where(:deleted=>0)
      @list_question_levels = QuestionLevel.where(:deleted=>0)
      @list_match_types = MatchType.where(:deleted=>0)
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 56
      answer_format = AnswerFormat.find(params[:id])
      answer_format.attributes = params[:answer_format]

      begin
        if answer_format.save
          str_desc="Se editó el answer format "+answer_format.name+" con id = "+answer_format.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer_format)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 57
      begin
        if AnswerFormat.delete(params[:id])
          str_desc="Se eliminó el answer format "+AnswerFormat.find(params[:id]).name+" con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

end

app/controllers/match_management/exam_topic_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::ExamTopicController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    if current_user.has_access 23
      @search = ExamTopic.search(params[:search])
      @list_exam_topics = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 24
      @exam_topic = ExamTopic.new
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 24
      exam_topic = ExamTopic.new(params[:exam_topic])
      begin
        if exam_topic.save
          str_desc="Se registró el exam topic "+exam_topic.name+" con id = "+exam_topic.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(exam_topic)
          redirect_to :action=>"new",:exam_topic=>exam_topic.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:exam_topic=>exam_topic.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 25
      @exam_topic = ExamTopic.find(params[:id])
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 26
      @exam_topic = ExamTopic.find(params[:id])
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 26
      exam_topic = ExamTopic.find(params[:id])
      exam_topic.attributes = params[:exam_topic]

      begin
        if exam_topic.save
          str_desc="Se editó el exam topic "+exam_topic.name+" con id = "+exam_topic.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(exam_topic)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 27
      begin
        if ExamTopic.delete(params[:id])
          str_desc="Se eliminó el exam topic "+ExamTopic.find(params[:id]).name+" con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

end

app/helpers/match_management/answer_format_helper.rb
module MatchManagement::AnswerFormatHelper
end

app/helpers/match_management/answer_helper.rb
module MatchManagement::AnswerHelper
end

app/helpers/match_management/exam_helper.rb
module MatchManagement::ExamHelper
end

app/helpers/match_management/exam_topic_helper.rb
module MatchManagement::ExamTopicHelper
end

app/helpers/match_management/match_helper.rb
module MatchManagement::MatchHelper
end

app/helpers/match_management/match_type_helper.rb
module MatchManagement::MatchTypeHelper
end

app/helpers/match_management/question_helper.rb
module MatchManagement::QuestionHelper
end

app/helpers/match_management/question_level_helper.rb
module MatchManagement::QuestionLevelHelper
end

app/views/match_management/match/_buttons.html.erb
<%if @int_page_type==0%>
  <%= submit_tag(t('buttons.register'), :disable_with => t('buttons.processing'), :class=>"btn btn-success")%>          
<%elsif @int_page_type==1%>
  <%= link_to t('buttons.enable_edition'), edit_match_management_match_path(@match), :class=>"button" unless !current_user.has_access(26) %>
<%else%>
  <%= submit_tag(t('buttons.edit'), :disable_with => t('buttons.processing'), :class=>"btn btn-info")%>      
  <%= link_to t('buttons.undo_changes'), edit_match_management_match_path(@match), :class=>"button"  %>
<%end%>
<%= link_to t('buttons.cancel'), match_management_match_index_path, :class=>"btn"%>

app/views/match_management/match/_form.html.erb
<%str_method = @int_page_type==2? 'put' : 'post'%>
<%str_path = @int_page_type==2? match_management_match_path : match_management_match_index_path%>
<%= form_for(@match, :url=>str_path, :method=>str_method,:html=>{:id=>"form_company"}, :class=>"form-horizontal") do |f| %>   
      
    <div class="control-group">
        <%= set_label_obligatory(Match.null?("name")) %><%= f.label :name,"#{t('.name')}:" %>
        <div class="controls">
          <%= f.text_field :name, :class=>"medium validate[#{set_validate(Match.null?("name"))}] input-xxlarge",:size=>50, :placeholder=>"#{t('.enter_the_name_survey')}" %>
        </div>
    </div>

        <dt><%= set_label_obligatory(Match.null?("url")) %><%= f.label :url,"#{t('.url')}:" %></dt>
        <dd>
          <%= f.text_field :url, :class=>"medium validate[#{set_validate(Match.null?("url"))}]",:size=>50 %>
          <small><%= t('.small_url')%></small>
        </dd>

        <dt><%= set_label_obligatory(Match.null?("started")) %><%= f.label :started,"#{t('.started')}:" %></dt>
        <dd>
          <%= f.text_field :started, :class=>"medium validate[#{set_validate(Match.null?("started"))}]",:size=>50 %>
          <small><%= t('.small_started')%></small>
        </dd>

        <dt><%= set_label_obligatory(Match.null?("match_type_id")) %><%= f.label :match_type_id,"#{t('.match_type')}:" %></dt>
        <dd>
          <%= f.select :match_type_id,@list_match_types.collect {|t| [t.name,t.id]},{:include_blank=>"#{t('.select_match_type')}"},{:class=>"medium validate[#{set_validate(Match.null?("match_type_id"))}]"} %>
          <small><%=t('.small_match_type_id')%></small>
        </dd>

        <dt><%= set_label_obligatory(Match.null?("question_level_id")) %><%= f.label :question_level_id,"#{t('.question_level')}:" %></dt>
        <dd>
          <%= f.select :question_level_id,@list_question_levels.collect {|t| [t.range,t.id]},{:include_blank=>"#{t('.select_question_level')}"},{:class=>"medium validate[#{set_validate(Match.null?("question_level_id"))}]"} %>
          <small><%=t('.small_question_level_id')%></small>
        </dd>
        <dt><%= set_label_obligatory(Match.null?("user_id")) %><%= f.label :user_id,"#{t('.user')}:" %></dt>
        <dd>
          <%= f.select :user_id,@list_users.collect {|t| [t.name,t.id]},{:include_blank=>"#{t('.select_user')}"},{:class=>"medium validate[#{set_validate(Match.null?("user_id"))}]"} %>
          <small><%=t('.small_user_id')%></small>
        </dd>

		<div style="clear:both"></div>
    <div class="buttons">
      <%= render :partial => "buttons" %>
    </div>
    
<% end %>

app/views/match_management/match/_search.html.erb
<a href="#" class="show_hide_form_search btn" onclick="open_close_div_search('form_search'); return false;"><i class="icon-search"></i> Search Filters</a>
<div style="clear:both"></div>

<%= form_for @search, :url => match_management_match_index_path, :html => {:method => :get, :id=>'form_search', :style=>'display:none', :remote=>true} do |f| %>
  <fieldset>
    <legend><%=t('search.search')%></legend>
    <dl class="inline">
      <dt><%= f.label t('.name') %></dt>
      <dd><%= f.text_field :name_contains %></dd>
    </dl>
    <div class="buttons">
      <%= submit_tag(t('search.search'), :disable_with => t('buttons.processing'), :class => "btn")%>          
      <span id='loading_search' style='display:none'><img alt='Loading' border='0' height='14' src="<%=image_path('style/loading.gif')%>" width='14'></span>
    </div>
  </fieldset>
<% end %>

<%=search_loading_js 'form_search'%>

app/views/match_management/match/_table.html.erb
<% if @list_matches.size > 0 %>
	<table id="table1" class="table table-hover">
		<thead>
			<tr>
				<th><%=t('.name')%></th>
				<th><%=t('.started')%></th>
				<th><%=t('.created_by')%></th>
				<th><%=t('table.actions')%></th>
			</tr>
		</thead>
		<tbody>
	    <%@list_matches.each do |match|%>
			  <tr>
				  <td><%=match.name%></td>
				  <td><%=match.get_status(match.started)%></td>
				  <td><%=match.user.name%></td>
				  <td>
					  <%=link_to image_tag('standard/show.png',:title=>"#{t('table.show')} #{match.name}"),edit_match_management_match_path(match) unless !current_user.has_access(19)%>
	                <%=link_to image_tag('standard/delete.png', :title=>"#{t('table.delete')} #{match.name}"),{:action=>'destroy',:id=>match.id},{:method=>:delete, :confirm=>t('messages.sure_to_delete')+match.name+"?"} unless !current_user.has_access(21)%>
				  </td>
			  </tr>
	    <%end%>
		</tbody>
	</table>
	<div class="tablefooter clearfix">
		<div class="pagination">
	    <%= will_paginate @list_matches %>
	    <%= paginate_ajax_js%>
		</div>
	</div>
<%else%>
	<p><%= t('messages.noitem_found')%></p>
<%end%>

app/views/match_management/match/edit.html.erb
<% title t('.title')+' '+ @match.name %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_match'} %>

app/views/match_management/match/index.html.erb
<% title t('.title') %>
<h2><%=yield :title%></h2>
<%= render :partial=>"layouts/messages" %>
<%= render :partial => "search" %><br/>
<div id="table">
  <%= render :partial => "table" %>
</div>
<br/><%= link_to t('.new_button'),new_match_management_match_path, :class=>"btn btn-info" unless !current_user.has_access(24)%>

app/views/match_management/match/index.js.erb
$('#table').html('<%=escape_javascript render :partial => "table" %>');

app/views/match_management/match/match_panel.html.erb
<% title t('.title') %>
<% list_access = Access.where(:parent_id=>22)%>

<% title t('panel.matches_management') %>
<%= render :partial=>"layouts/messages" %>
<h1><%= t('panel.match_welcome')%></h1>
<%= render :partial=>"layouts/panel_admin", :locals=>{:list_access=>list_access}%>

app/views/match_management/match/new.html.erb
<% title t('.title') %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_match'} %>

app/views/match_management/match/show.html.erb
<% title @match.name %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%=disabled_info 'form_match'%>