config/routes.rb
SurveyHuman::Application.routes.draw do

  resources :courses

  namespace :panel do resources :organizations end
  namespace :panel do resources :organization_invitations end

  get "report/index"
  namespace :panel do resources :subscription_transactions end

  get "/gateways/update-default-gateway/:id/:task", :to => "panel/gateways#update_default_gateway" ,\
  :as => 'update_default_gateway'

  get "/organization-invitation/update-status/:id/:status",
      :to => "panel/organization_invitations#update_status",
      :as => 'organization_invitation_update_status'

  post "/panel/deals/send-deal",
    :to => "panel/deals#send_deal",
    :as => 'send_deal'

  namespace :panel do
    resources :gateways do
    end
  end

  namespace :panel do resources :planfeatures end

  namespace :panel do resources :features end

  namespace :panel do resources :subscriptions end

  namespace :panel do resources :deals end

  namespace :panel do resources :plans end

  namespace :panel do resources :billings end

  resources :countries

  get "survey/index"

  get "front/sign_up"

  get "payment_notification/create"

  devise_for :users, :path => "", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }, :controllers => { :confirmations => "confirmations" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "home", :to => "devise/sessions#homepage"
    get "sign_up", :to => "devise/registrations#new"
  end

  namespace :account_management do
    resources :user do
      get :dashboard, :on => :collection
      get :account_panel, :on => :collection
      get :export_to_spreadsheet, :on => :collection
      post :create_user_by_sign_up, :on => :collection
    end
    resources :profile
    resources :log
    resources :company
  end

  namespace :match_management do
    resources :match do 
      get :match_panel, :on => :collection
      get :show_matches_by_match_type, :on => :collection
    end
    resources :survey do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_survey, :on=>:collection
      get :distribute, :on=>:collection
      put :send_survey_by_email, :on=>:collection
    end
    resources :exam do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_exam, :on=>:collection
      get :distribute, :on=>:collection
      put :send_exam_by_email, :on=>:collection
    end
    resources :match_type
    resources :question do
      post :add_question, :on=>:collection
      put :edit_question, :on=>:collection
      put :choose_correct_answer, :on=>:collection
    end
    resources :answer do
      put :add_answers, :on=>:collection
      put :edit_answers, :on=>:collection
    end
    resources :question_level
    resources :question_type
    resources :exam_topic
    resources :answer_format
    
  end

  namespace :organization_management do
    resources :company do 
      get :organization_panel, :on => :collection
    end
  end

  namespace :panel do
    resources :survey do
      post :submit_survey, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :exam do
      post :validate_user, :on => :collection
      get :forgot_password, :on => :collection
      post :send_password, :on => :collection
      get :new_code, :on => :collection
      post :create_code, :on => :collection
      get :show_exam, :on => :collection
      post :submit_exam, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :subscribe do
      get :index, :on => :collection
      get :edit, :on => :collection
      get :update, :on => :collection
    end
  end

  namespace :reports_management do
    resources :report do
      get :show_question , :on => :collection
      get :export_pdf, :on=> :collection
      get :show_result_student, :on=> :collection
      put :complete_result, :on=> :collection
    end
  end

  root :controller=>"account_management/user", :action=>"dashboard"

end

app/controllers/match_management/answer_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::AnswerController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    @current_view = "match"
    if current_user.has_access 48
      @search = Answer.search(params[:search])
      @list_answers = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      @list_questions = Question.where(:deleted=>0)
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 49
      @answer = Answer.new
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 49
      answer = Answer.new(params[:answer])
      begin
        if answer.save
          str_desc="Se registró el answer con id = "+answer.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer)
          redirect_to :action=>"new",:answer=>answer.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:answer=>answer.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 50
      @answer = Answer.find(params[:id])
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 51
      @answer = Answer.find(params[:id])
      @list_questions = Question.where(:deleted=>0)
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 51
      answer = Answer.find(params[:id])
      answer.attributes = params[:answer]

      begin
        if answer.save
          str_desc="Se editó el answer con id = "+answer.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 52
      begin
        if Answer.delete(params[:id])
          str_desc="Se eliminó el answer con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

  def add_answers
    if current_user.has_access 49
      #answer = Answer.new(params[:answer])
      question = Question.find params[:id]
      if !params[:question].nil?
        if Answer.where(:question_id=>question.id,:deleted=>0).count<=50
          params[:question][:answers_attributes].values.each do |answer|
            if answer[:_destroy]==false
                @answer=Answer.create!({:answer=>answer[:answer],:question_id=>question.id})
            end
          end
          question.attributes = params[:question]
          redirect_str= question.match.match_type_id==1 ? "/match_management/survey/#{question.match_id}/edit" : "/match_management/exam/#{question.match_id}/edit"
          begin
            if question.save
              str_desc="Se registró answers para la pregunta con id = "+question.id.to_s
              @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
              flash[:notice] = t('messages.successfully_created')
              redirect_to(redirect_str)
            else
              flash[:alert] = get_errors(answer)
              redirect_to(redirect_str)
            end
          rescue ActiveRecord::StatementInvalid => error
            flash[:alert] = t('messages.error_ocurred')
            redirect_to(redirect_str)
          end
        else
          flash[:alert] = "You cannot add more answers. Has been added 50 answers."
          redirect_to(redirect_str)
        end
      else
        redirect_str= question.match.match_type_id==1 ? "/match_management/survey/#{question.match_id}/edit" : "/match_management/exam/#{question.match_id}/edit"
        flash[:notice] = "You have not added any answer to the selected question."
        redirect_to(redirect_str)
      end
    else
      no_access
    end
  end

end

app/controllers/match_management/answer_format_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::AnswerFormatController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    @current_view = "match"
    if current_user.has_access 53
      @search = AnswerFormat.search(params[:search])
      @list_answer_formats = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 54
      @answer_format = AnswerFormat.new
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 54
      answer_format = AnswerFormat.new(params[:answer_format])
      begin
        if answer_format.save
          str_desc="Se registró el answer format "+answer_format.name+" con id = "+answer_format.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer_format)
          redirect_to :action=>"new",:answer_format=>answer_format.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:answer_format=>answer_format.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 55
      @answer_format = AnswerFormat.find(params[:id])
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 56
      @answer_format = AnswerFormat.find(params[:id])
      @list_users = User.where(:deleted=>0)
      @list_question_levels = QuestionLevel.where(:deleted=>0)
      @list_match_types = MatchType.where(:deleted=>0)
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 56
      answer_format = AnswerFormat.find(params[:id])
      answer_format.attributes = params[:answer_format]

      begin
        if answer_format.save
          str_desc="Se editó el answer format "+answer_format.name+" con id = "+answer_format.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(answer_format)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 57
      begin
        if AnswerFormat.delete(params[:id])
          str_desc="Se eliminó el answer format "+AnswerFormat.find(params[:id]).name+" con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

end

app/controllers/match_management/exam_topic_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class MatchManagement::ExamTopicController < ApplicationController
	layout "_content"
  before_filter :authenticate_user!
  def index
    if current_user.has_access 23
      @search = ExamTopic.search(params[:search])
      @list_exam_topics = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
      respond_to do |format|
        format.html
        format.js
      end
    else
      no_access
    end
  end

  def new
    if current_user.has_access 24
      @exam_topic = ExamTopic.new
      @int_page_type = 0
    else
      no_access
    end
  end

  def create
    if current_user.has_access 24
      exam_topic = ExamTopic.new(params[:exam_topic])
      begin
        if exam_topic.save
          str_desc="Se registró el exam topic "+exam_topic.name+" con id = "+exam_topic.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(exam_topic)
          redirect_to :action=>"new",:exam_topic=>exam_topic.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:exam_topic=>exam_topic.attributes
      end
    else
      no_access
    end
  end

  def show
    if current_user.has_access 25
      @exam_topic = ExamTopic.find(params[:id])
      @int_page_type = 1
    else
      no_access
    end
  end

  def edit
    if current_user.has_access 26
      @exam_topic = ExamTopic.find(params[:id])
      @int_page_type = 2
    else
      no_access
    end
  end

  def update
    if current_user.has_access 26
      exam_topic = ExamTopic.find(params[:id])
      exam_topic.attributes = params[:exam_topic]

      begin
        if exam_topic.save
          str_desc="Se editó el exam topic "+exam_topic.name+" con id = "+exam_topic.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(exam_topic)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

  def destroy
    if current_user.has_access 27
      begin
        if ExamTopic.delete(params[:id])
          str_desc="Se eliminó el exam topic "+ExamTopic.find(params[:id]).name+" con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
  end

end

app/helpers/match_management/answer_format_helper.rb
module MatchManagement::AnswerFormatHelper
end

app/helpers/match_management/answer_helper.rb
module MatchManagement::AnswerHelper
end

app/helpers/match_management/exam_helper.rb
module MatchManagement::ExamHelper
end

app/helpers/match_management/exam_topic_helper.rb
module MatchManagement::ExamTopicHelper
end

app/helpers/match_management/match_helper.rb
module MatchManagement::MatchHelper
end

app/helpers/match_management/match_type_helper.rb
module MatchManagement::MatchTypeHelper
end

app/helpers/match_management/question_helper.rb
module MatchManagement::QuestionHelper
end

app/helpers/match_management/question_level_helper.rb
module MatchManagement::QuestionLevelHelper
end

app/helpers/match_management/question_type_helper.rb
module MatchManagement::QuestionTypeHelper
end

app/views/match_management/survey/_answers_list.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<td>#</td>
			<td>Answers</td>
		</tr>
	</thead>
	<tbody>
		<%Answer.get_answers_by_question_id(question.id).each_with_index do |answer, index|%>
			<tr>
				<td><small><%=index+1%></small></td>
				<td><%=answer.answer%></td>
			</tr>
		<%end%>
	</tbody>
		
</table>

app/views/match_management/survey/_buttons.html.erb
<%if @int_page_type==0%>
  <%= submit_tag(t('buttons.register'), :disable_with => t('buttons.processing'), :class=>"btn btn-success")%>          
<%elsif @int_page_type==1%>
  <%= link_to t('buttons.enable_edition'), edit_match_management_survey_path(@match), :class=>"button inline" unless !current_user.has_access(26) %>
<%else%>
  <%= submit_tag(t('buttons.edit'), :disable_with => t('buttons.processing'), :class=>"btn btn-success inline")%>      
<%end%>
<%= link_to t('buttons.cancel'), match_management_survey_index_path, :class=>"btn inline"%>
<br/>

app/views/match_management/survey/_form.html.erb
<%str_method = @int_page_type==2? 'put' : 'post'%>
<%str_path = @int_page_type==2? match_management_survey_path : match_management_survey_index_path%>
<%= form_for(@match, :url=>str_path, :method=>str_method,:html=>{:id=>"form_match"}, :class=>"form-horizontal") do |f| %>
    <div class="control-group">
        <div class="controls span4">
          <%= f.label :name,"* #{t('.name')}"%>
          <%= f.text_field :name, :class=>"inline medium validate[#{set_validate(Match.null?("name"))}] input-xlarge",:size=>50, :placeholder=>"#{t('.enter_the_name_survey')}" %>
        </div>
        <%if @int_page_type==2%>
          <div class="controls span3">
            <%= f.label :started,"* #{t('.status')}"%>
            <%= f.select :started, @list_status.collect {|t| [t["name"],t["id"]]},{:class=>"medium validate[#{set_validate(Match.null?("started"))}]"} %>
          </div>
        <%end%>
        <%if current_user.profile_id==1%>
            <div class="controls span4">
              <%= f.label :user_id,"* #{t('.created_by')}"%>
              <%= f.select :user_id,@list_users.collect {|t| [t.name,t.id]},{:include_blank=>"#{t('.select_user')}"},{:class=>"validate[#{set_validate(Match.null?("user_id"))}]"} %>
            </div>
            <div class="controls span1">
              <%= render :partial => "buttons" %>
            </div>
        <%else%>
            <div class="controls span5">
              <%= render :partial => "buttons" %>
            </div>
        <%end%>
    </div>
<% end %>
<br/><br/><br/>
<small>If the suvey is finished, this will not be able to edit.</small>
<%if current_user.profile_id!=1%>
  <%if @int_page_type==2%>
    <div class="control-group">
      <h3><%=t('.questions') %>
      <a class="btn btn-info" href="#add-question-link" role="button" data-toggle="modal">Add Question</a></h3>
    </div>
    <%= render :partial => "questions_list" %>
  <%end%>
<%end%>

<%if @int_page_type==2 %>
  <div class="modal hide fade" id="add-question-link" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <%= render :partial => "match_management/question/add_question_dialog" %>
  </div>
<%end%>
<br/>
<br/>
<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<%= javascript_include_tag "jquery-ui-timepicker-addon" %>

app/views/match_management/survey/_questions_list.html.erb
<%if !@list_questions.empty?%>
    <div class="control-group">
      <%@list_questions.each_with_index do |question,index|%>
        <div class="question-div">
          <div class="controls controls-row">
            <div class="span6">
              <h5><%=index+1%>. <%=question.question%> <small><%=question.answer_format.name%></small></h5>
            </div>
            <div class="span3">
              <%if !question.image_attch_file_name.nil?%>
                <%= image_tag question.image_attch.url, :style=>"height:100px" %>
              <%else%>
                <small>No image</small>
              <% end %>
            </div>
            <div class="span2">
              <a id="edit-question-<%=question.id%>" class="btn btn-success" href="#edit-question-link-<%=question.id%>" role="button" data-toggle="modal"><i class='icon-pencil icon-white'></i></a>
              <%=link_to "<i class='icon-remove icon-white'></i>".html_safe, {:action=>'delete_question',:id=>question.id},{:method=>:delete, :confirm=>t('messages.sure_to_delete')+question.question+"?", :class=>"btn btn-danger", :role=>"button"} unless !current_user.has_access(47)%>
            </div>
          </div>

          <%obli = question.obligatory==1 ? "This question is obligatory " : "This question is NOT obligatory "%>
          <h6><%=obli%></h6>

          <%= render :partial => "match_management/question/edit_question_dialog", :locals=>{:id=>question.id}%>

      <%case question.answer_format_id%>
        <%when 3,4,7,8%>
          <small>The answer will be inserted by the user.</small>
        <%else%>
          <div style="padding-left:20px;">
            <%if !Answer.get_answers_by_question_id(question.id).empty?%>
              <%= render :partial => "answers_list", :locals=>{:question=>question}%>
              <a class="btn" href="#edit-answer-link-<%=question.id%>" role="button" data-toggle="modal"><small>Edit Answers</small></a>
              <div class="modal hide fade" id="edit-answer-link-<%=question.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <%= render :partial => "match_management/answer/add_answer_dialog", :locals=>{:question=>question}%>
                </div>
            <%else%>
                <small class="span5">No answers. These answers will be selected by the user.</small>
                <a class="btn" href="#add-answer-link-<%=question.id%>" role="button" data-toggle="modal"><small>Add Answers</small></a>
                <div class="modal hide fade" id="add-answer-link-<%=question.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <%= render :partial => "match_management/answer/add_answer_dialog", :locals=>{:question=>question}%>
                </div>
            <%end%>
          </div>
      <%end%>

        </div>
      <%end%>
    </div>
<%else%>
    <small>No questions</small>
<%end%>

app/views/match_management/survey/_send_email.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3>Email <small><%=@match.url%></small></h3>
</div>

<%= form_tag(send_survey_by_email_match_management_survey_index_path+'&id='+@match.id.to_s, :method=>"put") do %>   
  <div class="modal-body">
      <div class="control-group">
			  <label class="control-label" for="inputIcon">Email address</label>
			  <div class="controls">
			    <div class="input-prepend">
			      <span class="add-on"><i class="icon-envelope"></i></span>
			      <textarea class="span2" id="inputIcon" type="text" name="emails" style="max-width: 495px; max-height:50px; width: 495px; height:50px;" placeholder="user1@surveyhumans.com, user2@surveyhumans.com,"></textarea>
			    </div>
			  </div>
			  <label class="control-label" for="inputIcon">Message</label>
			  <div class="controls">
			    <div class="input-prepend">
			    	<span class="add-on"><i class="icon-align-justify"></i></span>
			      <textarea class="span2" id="inputIcon" type="text" name="message" style="max-width: 495px; max-height:170px; width: 495px; height:170px; "></textarea>
			    </div>
			  </div>
		</div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" >Close</button>
    <%= submit_tag(t('buttons.send'), :disable_with => t('buttons.processing'), :class=>"btn btn-success", :dismiss=>"modal")%>
  </div>
<% end %>

		

app/views/match_management/survey/_table.html.erb
<% if @list_matches.size > 0 %>
	<table id="table1" class="table table-hover">
		<thead>
			<tr>
				<th><%=t('.name')%></th>
				<th><%=t('.status')%></th>
		  	<th>URL</th>
			<%if current_user.profile_id==1%>
				<th><%=t('.created_by')%></th>
				<th><%=t('.deleted?')%></th>
			<%end%>
				<th><%=t('table.actions')%></th>
			</tr>
		</thead>
		<tbody>
	    <%@list_matches.each do |match|%>
			  <tr>
				  <td><%=match.name%></td>
				  <td><%=match.get_status(match.started)%></td>
				<%if !match.url.nil?%>
					<td><a href="<%=match.url%>"><%=match.url%></a></td>
				<%else%>
					<td>The URL hasn't been generated.</td>
				<%end%>
				<%if current_user.profile_id==1%>
					<td><%=match.user.email%></td>
					<td><%=match.deleted?(match.id)%></td>
				<%end%>
				  <td>
					<%=link_to "Edit",edit_match_management_survey_path(match) unless !current_user.has_access(19)%>
	                <%=link_to "Delete",{:action=>'destroy',:id=>match.id},{:method=>:delete, :confirm=>t('messages.sure_to_delete')+match.name+"?"} unless !current_user.has_access(21)%>
				  </td>
			
			  </tr>
	    <%end%>
		</tbody>
	</table>
	<div class="tablefooter clearfix">
		<div class="pagination">
	    <%= will_paginate @list_matches %>
	    <%= paginate_ajax_js%>
		</div>
	</div>
<%else%>
	<p><%= t('messages.noitem_found')%></p>
<%end%>

app/views/match_management/survey/distribute.html.erb
<% title t('.title') %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%>
		<%if @match.url.nil?%>
      <%=link_to "Generate URL", generate_url_for_survey_match_management_survey_index_path+"&id="+@match.id.to_s, :class=>"btn" unless !current_user.has_access(21)%>
    <%else%>
      <small><a href="<%=@match.url%>"><%=@match.url%></a></small>
      <%=link_to "Cancel", edit_match_management_survey_path(@match), :class=>"btn" unless !current_user.has_access(21)%>
    <%end%>
</h2>
<br>
<h3><%=@match.name%></h3>
<div style="border-radius:8px;border:1px solid #ccc;padding:20px;margin:10px;">
  <!--Share Facebook -->
    <a class="btn btn-primary" href="<%=@facebook_url%>"><img src="/img/icon-fb.png"> Share Facebook</a>
  <!--Share Twitter -->
    <a class="btn btn-info" href="<%=@twitter_url%>" target="_blank"><img src="/img/icon-tw.png"> Share Twitter</a>
</div>  
<div style="border-radius:8px;border:1px solid #ccc;padding:20px;margin:10px;">
  <!--Share by email -->
  <a class="btn" href="#send-email" role="button" data-toggle="modal"><i class="icon-envelope"></i> Send Email</a>
  <div class="modal hide fade" id="send-email" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <%= render :partial => "send_email", :id=>@match.id.to_s %>
  </div>
</div>
<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_match'} %>

app/views/match_management/survey/edit.html.erb
<% title t('.title')%>
<%= render :partial=>"layouts/messages" %>

<%if @match.started!=2%>
<div style="border-radius:8px;border:1px solid #ccc;padding:7px;">
<h2><%=yield :title%>
        <%if @match.url.nil?%>
          <%=link_to "Generate URL", generate_url_for_survey_match_management_survey_index_path+"&id="+@match.id.to_s, :class=>"btn" unless !current_user.has_access(21)%>
    <%else%>
        <small><a href="<%=@match.url%>"><%=@match.url%></a></small>
        <%=link_to "Distribute", distribute_match_management_survey_index_path+"&id="+@match.id.to_s, :class=>"btn" unless !current_user.has_access(21)%>
    <%end%>
</h2>
</div>
<br>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_match'} %>
<%else%>
	<h2><%=yield :title%></h2>
	<h5><span style="color:gray;font-size:20px"><%=@match.name.upcase%></span> is not able to be edited.</h5>
<%end%>

app/views/match_management/survey/index.html.erb
<% title t('.title') %>
<h2><%=yield :title%></h2>
<%= render :partial=>"layouts/messages" %>
<%= render :partial => "search" %><br/>
<div id="table">
  <%= render :partial => "table" %>
</div>
</br>
<%if @can_add%>
  <% if @subscription.status == nil %>
    <%= link_to t('.new_button'),new_match_management_survey_path, :class=>"btn btn-info" unless !current_user.has_access(24)%>
  <% else %>
    <p>Update your subscription in order to create more surveys</p>
    <a href="<%= panel_subscribe_index_path %>" class="btn btn-success">Update your subscription</a>
  <% end %>
<%else%>
	<p>You cannot add more surveys, because you are subscribed: <%=@plan%></p>
<%end%>

app/views/match_management/survey/new.html.erb
<% title t('.survey_details') %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_match'} %>