config/routes.rb
SurveyHuman::Application.routes.draw do

  resources :courses

  namespace :panel do resources :organizations end
  namespace :panel do resources :organization_invitations end

  get "report/index"
  namespace :panel do resources :subscription_transactions end

  get "/gateways/update-default-gateway/:id/:task", :to => "panel/gateways#update_default_gateway" ,\
  :as => 'update_default_gateway'

  get "/organization-invitation/update-status/:id/:status",
      :to => "panel/organization_invitations#update_status",
      :as => 'organization_invitation_update_status'

  post "/panel/deals/send-deal",
    :to => "panel/deals#send_deal",
    :as => 'send_deal'

  namespace :panel do
    resources :gateways do
    end
  end

  namespace :panel do resources :planfeatures end

  namespace :panel do resources :features end

  namespace :panel do resources :subscriptions end

  namespace :panel do resources :deals end

  namespace :panel do resources :plans end

  namespace :panel do resources :billings end

  resources :countries

  get "survey/index"

  get "front/sign_up"

  get "payment_notification/create"

  devise_for :users, :path => "", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }, :controllers => { :confirmations => "confirmations" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "home", :to => "devise/sessions#homepage"
    get "sign_up", :to => "devise/registrations#new"
  end

  namespace :account_management do
    resources :user do
      get :dashboard, :on => :collection
      get :account_panel, :on => :collection
      get :export_to_spreadsheet, :on => :collection
      post :create_user_by_sign_up, :on => :collection
    end
    resources :profile
    resources :log
    resources :company
  end

  namespace :match_management do
    resources :match do 
      get :match_panel, :on => :collection
      get :show_matches_by_match_type, :on => :collection
    end
    resources :survey do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_survey, :on=>:collection
      get :distribute, :on=>:collection
      put :send_survey_by_email, :on=>:collection
    end
    resources :exam do
      delete :delete_question, :on=>:collection
      delete :delete_answer, :on=>:collection
      get :generate_url_for_exam, :on=>:collection
      get :distribute, :on=>:collection
      put :send_exam_by_email, :on=>:collection
    end
    resources :match_type
    resources :question do
      post :add_question, :on=>:collection
      put :edit_question, :on=>:collection
      put :choose_correct_answer, :on=>:collection
    end
    resources :answer do
      put :add_answers, :on=>:collection
      put :edit_answers, :on=>:collection
    end
    resources :question_level
    resources :question_type
    resources :exam_topic
    resources :answer_format
    
  end

  namespace :organization_management do
    resources :company do 
      get :organization_panel, :on => :collection
    end
  end

  namespace :panel do
    resources :survey do
      post :submit_survey, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :exam do
      post :validate_user, :on => :collection
      get :forgot_password, :on => :collection
      post :send_password, :on => :collection
      get :new_code, :on => :collection
      post :create_code, :on => :collection
      get :show_exam, :on => :collection
      post :submit_exam, :on => :collection
      get :success, :on => :collection
      get :error, :on => :collection
    end
    resources :subscribe do
      get :index, :on => :collection
      get :edit, :on => :collection
      get :update, :on => :collection
    end
  end

  namespace :reports_management do
    resources :report do
      get :show_question , :on => :collection
      get :export_pdf, :on=> :collection
      get :show_result_student, :on=> :collection
      put :complete_result, :on=> :collection
    end
  end

  root :controller=>"account_management/user", :action=>"dashboard"

end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :user
	has_many :company_users

	# This function evaluates if a column is nullable or not in the database
	#
	# * *args*
	#   - column(_string_) -> database column to be evaluated
	# * *returns*
	#   - if the column is nullable or not
	def self.null?(column)
		columns_hash[column].null
	end

	# This function change user state to deleted
	#
	# * *args*
	#   - id -> profile id
	# * *returns*
	#   - if the state update was successful or not
	def self.delete(id)
		return update_all({:deleted=>1, :updated_at=>Time.now},{:id=>id})
	end
end

app/controllers/organization_management/company_controller.rb
#encoding: utf-8
# * *Page* *types*
#   - *0* -> new page
#   - *1* -> show page
#   - *2* -> edit page
class OrganizationManagement::CompanyController < ApplicationController
	layout "_content"
	before_filter :authenticate_user!
  
	def index
		if current_user.has_access 17
			@search = Company.search(params[:search])
			@list_companies = @search.where(:deleted => 0).paginate(:page => params[:page]).order('id DESC')
			@list_users = User.where(:deleted=>0)
			respond_to do |format|
				format.html
				format.js
			end
		else
			no_access
		end
	end

	def new
		if current_user.has_access 18
      @company = Company.new
      @list_users = User.where(:deleted=>0)
      @int_page_type = 0
    else
      no_access
    end
	end

  def create
    if current_user.has_access 18
      company = Company.new(params[:company])
      company.user_id=current_user.id
#      company.user = current_user
      begin
        if company.save
          str_desc="Se registró el company "+company.name+" con id = "+company.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_created')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(company)
          redirect_to :action=>"new",:company=>company.attributes
        end
      rescue ActiveRecord::StatementInvalid => error
        puts error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"new",:company=>company.attributes
      end
    else
      no_access
    end
  end

	def show
		if current_user.has_access 19
      @company = Company.find(params[:id])
      @list_users = User.where(:deleted=>0)
      @int_page_type = 1
    else
      no_access
    end
	end

	def edit
		if current_user.has_access 20
      @company = Company.find(params[:id])
      @list_users = User.where(:deleted=>0)
      @int_page_type = 2
    else
      no_access
    end
	end

	def update
		if current_user.has_access 20
      company = Company.find(params[:id])
      company.attributes = params[:company]

      begin
        if company.save
          str_desc="Se editó el company "+company.name+" con id = "+company.id.to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_updated')
          redirect_to :action=>"index"
        else
          flash[:alert] = get_errors(company)
          redirect_to :action=>"edit",:id=>params[:id]
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
        redirect_to :action=>"edit",:id=>params[:id]
      end
    else
      no_access
    end
  end

	def destroy
		if current_user.has_access 21
      begin
        if Company.delete(params[:id])
          str_desc="Se eliminó el company "+Company.find(params[:id]).name+" con id = "+params[:id].to_s
          @log=Log.create!({:description=>str_desc, :user_id=>current_user.id})
          flash[:notice] = t('messages.successfully_deleted')
        else
          flash[:alert] = t('messages.error_ocurred')
        end
      rescue ActiveRecord::StatementInvalid => error
        flash[:alert] = t('messages.error_ocurred')
      end
      redirect_to :action=>"index"
    else
      no_access
    end
	end

	def organization_panel

	end

end

app/helpers/account_management/company_helper.rb
module AccountManagement::CompanyHelper
end

app/helpers/organization_management/company_helper.rb
module OrganizationManagement::CompanyHelper
end

app/views/organization_management/company/_buttons.html.erb
<%if @int_page_type==0%>
  <%= submit_tag(t('buttons.register'), :disable_with => t('buttons.processing'), :class => "btn btn-success")%>          
<%elsif @int_page_type==1%>
  <%= link_to t('buttons.enable_edition'), edit_organization_management_company_path(@company), :class=>"button" unless !current_user.has_access(20) %>
<%else%>
  <%= submit_tag(t('buttons.edit'), :disable_with => t('buttons.processing'), :class => "btn btn-success inline")%>      
  <%= link_to t('buttons.undo_changes'), edit_organization_management_company_path(@company), :class=>"btn btn-success inline"  %>
<%end%>
<%= link_to t('buttons.cancel'), organization_management_company_index_path, :class=>"btn inline"%>

app/views/organization_management/company/_form.html.erb
<%str_method = @int_page_type==2? 'put' : 'post'%>
<%str_path = @int_page_type==2? organization_management_company_path : organization_management_company_index_path%>
<%= form_for(@company, :url=>str_path, :method=>str_method,:html=>{:id=>"form_company"}) do |f| %>   
	
	<fieldset>
		<legend><%=t('.organization_details')%></legend>
    <dl class="inline">

      <dt><%= f.label :name,"#{t('.name')}:" %></dt>
      <dd>
        <%= f.text_field :name, :class=>"medium validate[#{set_validate(Company.null?("name"))}]",:size=>50 %>
        
      </dd>

      <%if current_user.profile_id==1%>
        <dt><%= f.label :name,"#{t('.name')}:" %></dt>
        <dd>
          <%= f.select :user_id,@list_users.collect {|t| [t.name,t.id]},{:include_blank=>"#{t('.select_user')}"},{:class=>"medium validate[#{set_validate(Company.null?("user_id"))}]"} %>
        </dd>
      <%end%>

		<div style="clear:both"></div>

	    <div class="buttons">
	      <%= render :partial => "buttons" %>
	    </div>
    </fieldset>

<% end %>

app/views/organization_management/company/_search.html.erb
<a href="#" class="show_hide_form_search btn" onclick="open_close_div_search('form_search'); return false;"><i class="icon-search"></i> Search Filters</a>
<div style="clear:both"></div>

<%= form_for @search, :url => organization_management_company_index_path, :html => {:method => :get, :id=>'form_search', :style=>'display:none', :remote=>true} do |f| %>
  <fieldset>
    <legend><%=t('search.search')%></legend>
    <dl class="inline">
      <dt><%= f.label t('.name') %></dt>
      <dd><%= f.text_field :name_contains %></dd>
      <dt><%= f.label t('.user') %></dt>
      <dd><%= f.select :user_id_eq,@list_users.collect {|t| [t.name,t.id]},{:include_blank=>"#{t('.all_users')}"} %></dd>
    </dl>
    <div class="buttons">
      <%= submit_tag(t('search.search'), :disable_with => t('buttons.processing'), :class => "btn")%>          
      <span id='loading_search' style='display:none'><img alt='Loading' border='0' height='14' src="<%=image_path('style/loading.gif')%>" width='14'></span>
    </div>
  </fieldset>
<% end %>

<%=search_loading_js 'form_search'%>

app/views/organization_management/company/_table.html.erb
<% if @list_companies.size > 0 %>
<table id="table1" class="table table-hover">
	<thead>
		<tr>
			<th><%=t('.name')%></th>
			<%if current_user.profile_id==1%>
				<th><%=t('.user')%></th>
			<%end%>
			<th><%=t('table.actions')%></th>
		</tr>
	</thead>
	<tbody>
    <%@list_companies.each do |company|%>
		  <tr>
			  <td><%=company.name%></td>
			  <%if current_user.profile_id==1%>
			  	<td><%=company.user.name%></td>
			  <%end%>
			  <td>
				  <%=link_to image_tag('standard/show.png',:title=>"#{t('table.show')} #{company.name}"),organization_management_company_path(company) unless !current_user.has_access(19)%>
                <%=link_to image_tag('standard/delete.png', :title=>"#{t('table.delete')} #{company.name}"),{:action=>'destroy',:id=>company.id},{:method=>:delete, :confirm=>t('messages.sure_to_delete')+company.name+"?"} unless !current_user.has_access(21)%>
			  </td>
		  </tr>
    <%end%>
	</tbody>
</table>
<div class="tablefooter clearfix">
	<div class="pagination">
    <%= will_paginate @list_companies %>
    <%= paginate_ajax_js%>
	</div>
</div>
<%else%>
<p><%= t('messages.noitem_found')%></p>
<%end%>

app/views/organization_management/company/edit.html.erb
<% title t('.title')+' '+ @company.name %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_company'} %>

app/views/organization_management/company/index.html.erb
<% title t('.title') %>
<h2><%=yield :title%></h2>
<%= render :partial=>"layouts/messages" %>
<%= render :partial => "search" %><br/>
<div id="table">
  <%= render :partial => "table" %>
</div>
<br/><%= link_to t('.new_organization'),new_organization_management_company_path, :class=>"btn btn-info" unless !current_user.has_access(18)%>

app/views/organization_management/company/new.html.erb
<% title t('.title') %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%= render :partial=>"layouts/validation",:locals=>{:form_id=>'form_company'} %>

app/views/organization_management/company/organization_panel.erb
<% title t('.title') %>
<% list_access = Access.where(:parent_id=>58)%>

<% title t('panel.organization_management') %>
<%= render :partial=>"layouts/messages" %>
<h1><%= t('panel.organization_welcome')%></h1>
<%if current_user.profile_id==1%>
<%= render :partial=>"layouts/panel_admin", :locals=>{:list_access=>list_access}%>
<%else%>
<%= render :partial=>"layouts/panel_user", :locals=>{:list_access=>list_access}%>
<%end%>

app/views/organization_management/company/show.html.erb
<% title @company.name %>
<%= render :partial=>"layouts/messages" %>

<h2><%=yield :title%></h2>
<%= render :partial => "form" %>

<%=disabled_info 'form_company'%>